name = "r0"
version = 5

[device]
family = "GW5AST-138B"
part = "GW5AST-LV138FPG676AES"

[hdl]
standard = "sysv2017"
top = "top"

[files]
verilog = [
  "src/**/*.sv",
  "src/**/*[!_tmp].v"
]
cst = "phy.cst"
# sdc = "timings.sdc"

[pnr]
place_option = 3
route_option = 1
replicate = true

[bitstream]
compress = true

[programmer]
fs = "impl/pnr/project.fs"

preset.sram = { op = "2" }
preset.spi = { op = "53" }
